package com.backend.utk.pdfProcessor.processor.cleaner;

import com.backend.utk.pdfProcessor.model.PdfPage;
import com.backend.utk.pdfProcessor.model.PdfParagraph;

import java.util.Iterator;
import java.util.function.Predicate;
import java.util.regex.Pattern;

public class MetadataCleaner extends AbstractCleaner {
    private static final Pattern URL_PATTERN =
            Pattern.compile("https?://\\S+|www\\.\\S+|\\S+.com", Pattern.CASE_INSENSITIVE);

    private static final Pattern[] COPYRIGHT_PATTERNS = {
            Pattern.compile("copyright", Pattern.CASE_INSENSITIVE),
            Pattern.compile("all rights reserved", Pattern.CASE_INSENSITIVE),
            Pattern.compile("public domain", Pattern.CASE_INSENSITIVE)
    };

    private static final Pattern[] DOWNLOAD_PATTERNS = {
            Pattern.compile("downloaded from", Pattern.CASE_INSENSITIVE),
            Pattern.compile("generated by", Pattern.CASE_INSENSITIVE),
            Pattern.compile("produced by", Pattern.CASE_INSENSITIVE),
            Pattern.compile("distributed by", Pattern.CASE_INSENSITIVE)
    };

    @Override
    public void clean(PdfPage page) {
        removeUrls(page);
        removeCopyrights(page);
        removeDownloadMessages(page);
        removeEmptyParagraphs(page);
    }

    private void removeUrls(PdfPage page) {
        filterParagraphs(page, text -> URL_PATTERN.matcher(text).find());
    }

    private void removeCopyrights(PdfPage page) {
        filterParagraphs(page, this::containsCopyright);
    }

    private void removeDownloadMessages(PdfPage page) {
        filterParagraphs(page, this::containsDownloadMessage);
    }

    private void removeEmptyParagraphs(PdfPage page) {
        filterParagraphs(page,
                text -> text == null || text.trim().isEmpty());
    }

    private boolean containsCopyright(String text) {
        for (Pattern pattern : COPYRIGHT_PATTERNS) {
            if (pattern.matcher(text).find()) {
                return true;
            }
        }
        return false;
    }

    private boolean containsDownloadMessage(String text) {
        for (Pattern pattern : DOWNLOAD_PATTERNS) {
            if (pattern.matcher(text).find()) {
                return true;
            }
        }
        return false;
    }

    private void filterParagraphs(
            PdfPage page,
            Predicate<String> predicate) {
        Iterator<PdfParagraph> iterator = page.getParagraphs().iterator();
        while (iterator.hasNext()) {
            PdfParagraph paragraph = iterator.next();
            if (predicate.test(paragraph.getText())) {
                iterator.remove();
            }
        }
    }

}